Esri/angular-esri-map

README.md, docs/index.html, gulpfile.js, test/README.md, test/feature-layers.html, test/legend.html, test/map-events.html, test/set-basemap.html, test/set-center-zoom.html, test/simple-map.html, test/web-map.html
also moved stand-alone pages from examples to test and added README
resolves #34
=> updated to JSAPI 3.12

CHANGELOG.md, README.md, test/add-remove-layers.html, test/additional-map-options.html, test/deferred-map.html, test/e2e/specs/set-center-zoom.js, test/feature-layers.html, test/legend.html, test/map-events.html, test/registry-pattern.html, test/set-basemap.html, test/set-center-zoom.html, test/simple-map.html, test/web-map.html
@tomwayson please review.  Resolves #95.
Please also see [this comment](https://github.com/Esri/angular-esri-map/issues/95#issuecomment-143462001) for a potential spin-off question/issue.
=> supported-angular-jsapi-versions-#95

CHANGELOG.md, test/add-remove-layers.html, test/additional-map-options.html, test/e2e/specs/add-remove-layers.js, test/e2e/specs/additional-map-options.js, test/e2e/specs/deferred-map.js, test/e2e/specs/registry-pattern.js, test/registry-pattern.html
@tomwayson please review. Resolves #89 by adding 4 e2e specs.  Might need to look into updating gh-pages as a couple of actual test pages have minor changes.
=> Additional integration tests #89

docs/app/examples/feature-layers.js, src/directives/esriFeatureLayer.js, src/directives/esriInfoTemplate.js, test/e2e/specs/feature-layers.js, test/feature-layers.html
@tomwayson please review.  Resolves #114.  I was really intrigued by the new implementation of the esriInfoTemplate, and wanted to learn the inner workings of it by _trying_ to tackle #114.  Neat stuff!
=> feature-layer-info-template

docs/app/examples/no-basemap.html, docs/app/examples/no-basemap.js, src/directives/esriMap.js, test/dynamic-map-service-layer.html, test/dynamic-map-service-layers.html, test/e2e/specs/dynamic-map-service-layers.js
@tomwayson please review.  Hopefully I interpreted the to do checklist items (particularly the 4th one) correctly for the multiple dynamic layers test page on #116 in [this change](https://github.com/Esri/angular-esri-map/compare/map-infoWindow-adjustments?expand=1#diff-69fc914125d0227576e254e65cd85b5bR87).  If not, I'll be happy to make additional changes.
Resolves #116, #115.
=> Map info window adjustments

docs/app/appConfig.js, docs/app/examples/custom-basemap.html, docs/app/examples/custom-basemap.js, docs/app/examples/dynamic-map-service-layer.html, docs/app/examples/dynamic-map-service-layers.html, docs/app/examples/dynamic-map-service-layers.js, docs/index.html
@tomwayson please review. Resolves #124.  Feel free to suggest if we should wire up some additional UI controls to help illustrate any additional concepts in these examples.
=> Additional docs pages

test/e2e/specs/legend.js, test/e2e/specs/web-map.js
@tomwayson this adds e2e for the legend test page. Please review and merge if satisfied. Resolves #139. Thank you.
=> legend-e2e-test

site/app/examples/dynamic-map-service-layers.html, site/app/examples/feature-layers.html, site/app/examples/legend.html, site/app/examples/no-basemap.html, site/app/examples/other-esri-modules.html, site/app/examples/simple-map.html, site/app/examples/web-map.html, src/core/esri.core.module.js, src/core/esriLoader.js, src/esri.map.module.js, src/layers/esriFeatureLayer.js, src/map/EsriMapController.js, src/map/esriLegend.js, src/map/esriMap.js
@tomwayson please review.  This is for https://github.com/esri/angular-esri-map/issues/99#issuecomment-156133889.  The checklist as of creating this PR should reflect what has been added to the documentation.
I also added some cross-referenced links between docs and some site example pages.
I couldn't get the ngdocs to generate content for the esri.map and esri.core docs pages, and also not fully sure if that is even a feature.
Feel free to edit heavily; some params and descriptions I really wasn't :100:% sure on and would love your feedback.
=> Api documentation

gulpfile.js, site/app/app.js, site/app/examples/add-remove-layers.html, site/app/examples/additional-map-options.html, site/app/examples/custom-basemap.html, site/app/examples/dynamic-map-service-layer.html, site/app/examples/dynamic-map-service-layers.html, site/app/examples/examples.html, site/app/examples/layer-events.html, site/app/examples/map-events.html, site/app/examples/registry-pattern.html, site/app/examples/set-basemap.html, site/app/examples/set-center-zoom.html, site/app/home/home.html, site/app/home/home.js, site/docs-resources/docs-main.css, site/docs-resources/docs-nav-template.html, site/index.html, src/core/esriRegistry.js, src/layers/EsriDynamicMapServiceLayerController.js, src/layers/EsriFeatureLayerController.js, src/layers/EsriLayerControllerBase.js, src/layers/esriDynamicMapServiceLayer.js, src/layers/esriFeatureLayer.js, src/layers/esriInfoTemplate.js, src/map/EsriMapController.js, src/map/esriMap.js
@tomwayson please review and refer to our mighty to-do checklist at https://github.com/Esri/angular-esri-map/issues/99#issuecomment-155486184.  Resolves #99 once the checklist is done.
Fyi I went ahead and checked "on" **core/esriMapUtils** for you, but for anyone else reading this, that is currently over in the **more-unit-tests** branch.
I think we've just got to coordinate on documenting **core/esriRegistry**.  Any chance that's also coming hand-in-hand with its unit tests?
Thanks!
=> Api docs continued

.travis.yml, package.json, test/unit/karma.conf.js
added karma firefox runner and configured travis to run tests in firefox
resolves #90
=> added travis config

site/index.html
Should prevent all the Mixed Content errors when delivered over HTTPS
=> Made libary URLs HTTP/HTTPS agnostic - i.e. protocol-relative

src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, test/deferred-map.html, test/feature-layer.html, test/scene-view.html
@tomwayson please review (after PR #206).  Resolves #202.
As an experiment, check out this line for handling JSAPI 4.x property watches outside of Angular. That's the only reason `$scope` was injected here. I would appreciate your feedback on that as well--it is going in the direction of good old #74!
https://github.com/Esri/angular-esri-map/commit/5acb9f829674476cda86dd6ebeed5b8e4f5a1f79#diff-eda3f33f6eb5cefe10d1df4b8d772466R72
=> Deferred test page #202

test/deferred-map.html, test/property-binding.html
Alright here's something that resolves #209, @tomwayson.  The extra info and table at the top is mainly to communicate with you and whoever else looks at the new test page what I've discovered so far with binding.  That content can get edited or blasted before merging this, esp. if we come up with a new example or patterns page later on.
=> new property-binding test page; moved binding out of deferred-map

src/map/esriLegend.js, test/e2e/specs/legend.js
@tomwayson please review.  This hopefully resolves #225.
=> Legend title bug #225

.travis.yml
=> travis should not build gh-pages branch

site/app/common/alertController.js, site/docs-resources/docs-nav-template.html, site/index.html, site/styles/main.css
=> added links to v1 docs and beta alert

site/app/appConfig.js, site/app/examples/property-binding.html, site/app/patterns/property-binding.html, test/property-binding.html
@tomwayson please give this a spin.  Resolves #234
=> patterns page for property binding

site/app/common/browserDetectionService.js, site/app/examples/chaining-promises.js, site/app/examples/extrude-polygon.js, site/app/examples/geodesic-buffers.js, site/app/examples/home-button.js, site/app/examples/scene-toggle-elevation.js, site/app/examples/scene-view.js, site/app/examples/search.js, site/app/examples/webscene-slides.js, site/index.html
=> Mobile sniffing

README.md
Resolves #249 
If this all makes sense, I'll work on v1.x-related changes after this.
=> readme-quickstart-#249

README.md
@tomwayson please review this PR into branch v1.x
resolves #248
=> updated all v1 docs links;

CHANGELOG.md, gulpfile.js, site/app/appConfig.js, site/app/examples/registry-pattern.html, site/app/examples/registry-pattern.js, site/app/patterns/references-to-views.html, site/docs-resources/esri.core.ngdoc, site/index.html, src/core/esriRegistry.js, src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, src/map/esriMapView.js, src/map/esriSceneView.js, test/e2e/specs/registry-pattern.js, test/e2e/specs/webscene-slides-as-directive.js, test/registry-pattern.html, test/unit/core/esriRegistry.spec.js
@tomwayson please review.  Thanks for your help earlier!
Resolves #255
=> esriRegistry for v2

CHANGELOG.md, README.md, site/app/examples/set-basemap.html, site/app/patterns/create-your-own-directives.html, site/app/patterns/references-to-map-and-layers.html, site/index.html, src/core/esriLoader.js, test/set-basemap.html, test/unit/core/esriLoader.spec.js
@tomwayson pls review. For whenever 3.16 is announced in the coming days, here are the changes for branch v1.x.
resolves #258
=> v1.x default to JSAPI 3.16

README.md
@jwasilgeo I remembered this right after publishing. pls review and merge. note that you can use `@1` to indicate the latest 1.x. So we should not need to keep updating this.
=> update npmcdn version in quickstart

CHANGELOG.md, README.md, bower.json, package.json
=> prep for v2.0.0-beta.1

README.md
Hey @tomwayson anything you'd like to edit or add from other presentations you've done or are aware of?
If it's all good, I can repeat for the v1.x branch README
=> added links to dev summit 2016 slides

site/index.html, site/styles/main.css
Resolves #276.  Will deploy to gh-pages after merging.
=> v1 docs site more mobile friendly:

CHANGELOG.md, README.md, src/core/esriLoader.js, src/map/EsriHomeButtonController.js, src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, src/map/esriHomeButton.js, test/README.md, test/chaining-promises.html, test/e2e/specs/chaining-promises.js, test/e2e/specs/feature-layer.js, test/e2e/specs/scene-toggle-elevation.js, test/extrude-polygon.html, test/feature-layer.html, test/geodesic-buffers.html, test/home-button.html, test/popups.html, test/property-binding.html, test/registry-pattern.html, test/scene-toggle-elevation.html, test/scene-view.html, test/search.html, test/unit/core/esriLoader.spec.js, test/vector-tiles.html, test/webscene-slides-as-directive.html, test/webscene-slides.html
This is the first PR as part of a larger effort to get this repo ready with JSAPI 4.0 release.  Please reference #278 for a full TO DO list that will be finalized in a future PR.
Here you can expect to find updates to:
- src code directives and controllers
- you can now specify a `view-ui-position` bound property for the home button
- ngDocs comments were updated, too
- test pages (you may notice all the `<meta>` tag updates...for consistency's sake I ran with the exact options I saw the JSAPI examples using.
- unit and e2e tests (sometimes the e2e registry-pattern test doesn't like the scene view--but the page is working...)
- test pages README
- main repo README (this is still a work in progress)
=> v2 and jsapi4: test pages and src

CHANGELOG.md, README.md, site/app/examples/add-remove-layers.html, site/app/examples/custom-basemap.html, site/app/examples/dynamic-map-service-layer.html, site/app/examples/dynamic-map-service-layers.html, site/app/examples/legend.html, site/app/examples/no-basemap.html, site/app/examples/other-esri-modules.html, site/app/examples/set-basemap.html, site/app/examples/simple-map.html, site/app/examples/vector-tile-layer.html, site/app/examples/web-map.html, site/index.html, src/core/esriLoader.js, test/add-remove-layers.html, test/custom-basemap.html, test/custom-directive.html, test/deferred-map.html, test/dynamic-map-service-layer.html, test/dynamic-map-service-layers.html, test/legend.html, test/other-esri-modules.html, test/set-basemap.html, test/simple-map.html, test/unit/core/esriLoader.spec.js, test/vector-tile-layer.html, test/web-map.html
@tomwayson do you have a moment to give this a quick review?  Resolves #283, now that JSAPI 3.17 is officially out.
I can publish the next tagged release once this gets on the **v1.x** branch.
=> Jsapi 317 #283

CHANGELOG.md, README.md, site/index.html
@tomwayson please review, and if you want to go ahead and merge.  I will apply the same changes to the v1 site/index.html and README after this is all settled.
Covers #285 (which we can close after applying changes to v1)
=> Readme angular1 vs 2

test/deferred-map.html
This includes a couple quick fixes for a few things that needed to change in the deferred-map test page.
=> Update deferred-map test page

CHANGELOG.md, site/app/appConfig.js, site/app/patterns/create-your-own-factories.html, site/app/patterns/references-to-views.html, test/custom-factory.html, test/e2e/specs/custom-factory.js
@tomwayson do you mind reviewing this, and also being a copy editor for the new patterns page content?  I feel that the phrasing and wording of a few things can be improved upon.
relates to #287
After we agree to these changes with whatever else you want to do or see done here, feel free to merge and delete the branch.  Then, I can go through porting this content and the new test page to the **v1** side.
=> Patterns factory

CHANGELOG.md, site/app/appConfig.js, site/app/patterns/create-your-own-factories.html, site/app/patterns/references-to-map-and-layers.html, test/custom-factory.html, test/e2e/specs/custom-factory.js
relates to #287, but specifically for v1 branch
PR #293 was for master branch
=> patterns factory v1

CHANGELOG.md, gulpfile.js, site/app/app.js, site/index.html, src/layers/EsriDynamicMapServiceLayerController.js, src/layers/EsriFeatureLayerController.js, src/layers/EsriVectorTileLayerController.js, src/map/EsriMapController.js, test/add-remove-layers.html, test/additional-map-options.html, test/custom-basemap.html, test/custom-directive.html, test/custom-factory.html, test/deferred-map.html, test/dynamic-map-service-layer.html, test/dynamic-map-service-layers.html, test/e2e/specs/set-center-zoom.js, test/feature-layers.html, test/layer-events.html, test/legend.html, test/map-events.html, test/other-esri-modules.html, test/registry-pattern.html, test/set-basemap.html, test/set-center-zoom.html, test/simple-map.html, test/vector-tile-layer.html, test/web-map-webmapid-param.html, test/web-map.html
resolves #318 
relates to #314 for master branch (once PR #320 and this PR are accepted and merged, then this issue is fully resolved)
=> 314 angular 1.6.0 bindings v1

CHANGELOG.md, gulpfile.js, site/app/app.js, site/index.html, src/map/EsriHomeButtonController.js, src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, test/chaining-promises.html, test/custom-factory.html, test/deferred-map.html, test/e2e/specs/deferred-map.js, test/extrude-polygon.html, test/feature-layer.html, test/geodesic-buffers.html, test/home-button.html, test/popups.html, test/property-binding.html, test/registry-pattern.html, test/scene-toggle-elevation.html, test/scene-view.html, test/search.html, test/vector-tiles.html, test/webscene-slides-as-directive.html, test/webscene-slides.html
resolves #319 
relates to #314 for master branch (I still have to apply the src code changes to v1 branch before that issue is fully resolved)
=> 314 angular 1.6.0 view options

CHANGELOG.md, README.md, site/index.html, src/core/esriLoader.js, test/unit/core/esriLoader.spec.js
resolves #316 
After merging, I will do the following:
- prep the repo for a new v1.x release (README deps table, package.json)
- publish a new v1.x release
- update the v1's gh-pages repo so that the public docs site has all the latest and greatest
Any other thoughts or suggestions, @tomwayson?  My tests ran fine btw.
=> jsapi-3.19

README.md
Proposed changes:
- One minor addition to README
- Adds one new link to an Ionic2 sample under the What about Angular 2? section.
=> added a link to an ionic2 sample

CHANGELOG.md, README.md, site/index.html, src/core/esriLoader.js, test/unit/core/esriLoader.spec.js
After this is accepted and merged, I will do the following:
- prep the repo for a new v1.x release (package.json)
- publish a new v1.x release to github and npm
- update the this branch's separate gh-pages repo so that the public docs site has all the latest and greatest
cc @andygup
=> jsapi-3.20

CHANGELOG.md, README.md, package-lock.json, site/index.html, src/core/esriLoader.js, test/unit/core/esriLoader.spec.js
After this is accepted and merged, I will do the following (likely not until week of 7/17):
- prep the repo for a new v1.x release (package.json)
- publish a new v1.x release to github and npm
- update the this branch's separate gh-pages repo so that the public docs site has all the latest and greatest
=> jsapi-3.21

.travis.yml, CHANGELOG.md, README.md, package.json, site/index.html
This relates to #339 and #340 for the `v1.x` branch (JSAPI 3.x).
@tomwayson and @andygup are you all ok with the language in the README?
Once this PR is settled and merged in I'll repeat these updates for the `master` branch (JSAPI 4.x).
=> v1 updates for 339 and 340

.travis.yml, CHANGELOG.md, README.md, package.json, site/app/patterns/property-binding.html, site/index.html
Following PR #341 which was for the v1.x branch, this PR introduces similar changes for the master branch.
Resolves #339 
Resolves #340 (a gh-pages deploy will need to happen after this PR)
=> master updates for 339 and 340

README.md
FYI, AngularJS going into maintenance mode on July 1, 2018
=> Add AngularJS maintenance mode notice
