Esri/angular-esri-map

src/services/esriLoader.js
Extended the esriLoader to support an argument type of array as well as a string. The promise will now resolve either a single object when a string is input or an Array<object> when an array of strings is provided.
=> Fix for: "esriLoader should take an array of module names and return an array of modules #45"

bower.json
The script files are both in the dist directory, jet the path for the angular-esri-map.min.js points to the parent directory. This fixes it.
=> fix script path

docs/app/examples/set-center-zoom.html, gulpfile.js, test/e2e/specs/feature-layers.js, test/e2e/specs/map-events.js, test/e2e/specs/set-center-zoom.js, test/e2e/specs/simple-map.js, test/e2e/specs/web-map.js, test/feature-layers.html, test/map-events.html, test/set-center-zoom.html
@jwasil when you get a chance please pull the latest and run/review the legend test I wrote
If it looks good, let's go ahead and merge.
=> Additional integration tests

CHANGELOG.md, docs/app/examples/feature-layers.html, docs/app/examples/feature-layers.js, src/directives/esriFeatureLayer.js, src/directives/esriMap.js, test/e2e/specs/feature-layers.js, test/feature-layers.html
@tomwayson please review. I modified the feature-layers example docs page a bit in 8515ae4, and perhaps even replicated too much functionality from the related test page.  Feel free to suggest cutting something from that.
The changelog has also been updated.  gh-pages should be updated after this PR as well.
Resolves #97 and #100.
Thanks!
=> Feature layer options

CHANGELOG.md, README.md, docs/app/examples/feature-layers.html, src/directives/esriFeatureLayer.js, src/directives/esriMap.js, test/e2e/specs/feature-layers.js, test/feature-layers.html
Please review. The primary changes here are to esriMap and esriFeatureLayer to work with the JSAPI map.addLayer optional `index` argument. The remaining changes are for relevant example and test pages, as well as updates to a readme snippet and the changelog.
Resolves #101.
=> Layer index ordering #101

CHANGELOG.md, docs/app/examples/additional-map-options.html, docs/app/examples/legend.html, src/directives/esriMap.js, test/legend.html
@tomwayson please review. Resolves #105.  Reminder: update gh-pages branch after this.
=> esriLegend-layer-ordering-#105

CHANGELOG.md, src/directives/esriDynamicMapServiceLayer.js, src/directives/esriFeatureLayer.js, src/directives/esriMap.js, src/services/esriMapUtils.js
Update map and layer directives to use `controllerAs` and `bindToController` instead of injecting `$socpe` into controllers.
resolves #109
=> controllerAs and bindToController

docs/app/examples/other-esri-modules.html, docs/app/examples/other-esri-modules.js, docs/index.html
I've been independently working with angular and the Esri Draw toolbar and recently noticed that applying an `opacity` rule for the draw mouse tooltip is necessary to show it on the map.  I've seen this both in this repo's docs gh-pages as well as in another app using angular material design.
I also went with button function binding so that the same tool can be activated back-to-back after a `draw-end`.
If you're good with these changes, feel free to go ahead and take care of this PR, or I can deal with it myself.
Reminder to us: please deploy to gh-pages as well.
Thanks!
=> other-esri-modules-docs-fix

gulpfile.js, package.json, src/core/esriLayerUtils.js, test/unit/.eslintrc, test/unit/core/esriLayerUtils.spec.js, test/unit/core/esriLoader.spec.js, test/unit/karma.conf.js
I think the patterns I've set up in the esriLayerUtils spec will work well for most of the other services and controllers. It's not perfect, but it will serve as the foundation for writing other tests.
There's probably a more Angularish way to fake esriLoader's `require()` like [using ngMock's deferred](http://www.bradoncode.com/blog/2015/07/25/tip-unit-test-promise-angular/) rather than creating my own mock promise object), but that looks like a big hassle. I'm pretty sure we'll have to do something like that to test the functions in esriLoader - or maybe just spy on `window.require()`? I'm definitely open to suggestions here, but right now the tests are testing the right code, run fast, and are pretty easy to set up.
Also, w/ grunt, I'm used to [configuring karma's server to run in the …
=> Added Karma for unit testing

.gitignore, gulpfile.js, package.json, site/app/examples/custom-basemap.js, src/core/esriLayerUtils.js, src/core/esriMapUtils.js, test/custom-basemap.html, test/unit/core/esriLayerUtils.spec.js, test/unit/core/esriLoader.spec.js, test/unit/core/esriMapUtils.spec.js, test/unit/core/esriRegistry.spec.js, test/unit/karma.conf.js
Resolves #146 
Couldn't get tests to work for `esriMapUtils.createWebMap()`, but those can be added later. Otherwise I'm happy w/ the tests for the loader and map and layer utils.
@jwasil please review and merge at will.
=> Unit tests for esri.core services

gulpfile.js, site/app/home/home.html, site/docs-resources/esri.core.ngdoc, site/docs-resources/esri.map.ngdoc, site/docs-resources/index.ngdoc, site/index.html, src/core/esri.core.module.js, src/esri.map.module.js
@tomwayson I figured out the magic combination to get an index landing page wired up with our api documentation.  Now we need to just figure out the content we want.  Thoughts?  Then, that resolves #153.  Still no dice on documenting **esri.map** or **esri.core** modules.
=> api-docs-index

gulpfile.js, src/core/esriLoader.js, test/unit/core/esriLoader.spec.js
=> esriLoader tests for require instead of esri global

src/core/esriLayerUtils.js, src/core/esriLoader.js, src/core/esriMapUtils.js, src/layers/EsriDynamicMapServiceLayerController.js, src/layers/EsriLayerControllerBase.js, src/map/EsriMapController.js
in ES6 services and controllers will just be classes so
replace angular helper functions with vanilla JS
resolves #161
=> remove unnessary angular refs from service/controllers

site/app/examples/add-remove-layers.html, site/app/examples/custom-basemap.html, site/app/examples/dynamic-map-service-layer.html, site/app/examples/dynamic-map-service-layers.html, site/app/examples/feature-layers.html, site/app/examples/layer-events.html, site/app/examples/map-events.html, site/app/examples/no-basemap.html, site/index.html, site/styles/main.css
@tomwayson please review and also update gh-pages.
I mainly tried to fix the code snippet placement (Firefox actually exposed a bootstrap grid class error on my part), and also made snippets overflow-x instead of wrapping formatted code.  Was hoping that would make the snippets a bit clearer to follow.  
Also noticed that IE11 doesn't like (or rather, let's be honest: cannot ever be capable of understanding) custom tags that close themselves, e.g. `<esri-feature-layer />`, so I added closing tags where necessary.
As a final misc. task, I just worked on trying to make some of the html spacing a little more consistent throughout the examples.
As usual, all of this is up for debate.  Thanks!
=> site-styling

CHANGELOG.md, README.md, site/app/examples/set-basemap.html, site/index.html, src/core/esriLoader.js, test/set-basemap.html, test/unit/core/esriLoader.spec.js
@tomwayson please review.  Resolves #156.  A couple of notes:
- Seem to be some timing differences between `3.15amd` and `3.15compact`.  I'd recommend trying out both on the docs site and refreshing pages to see what you think.  How should we proceed with what **esriLoader** defaults to?
- My `gulp test` is hosed with running protractor tests.  My protractor, webdriver-manager, node, java, etc. deps seem to be fine and on my win PATH.  Have you seen this occurring on your end?  Right when `gulp-angular-protractor` is starting up.  So, I'm submitting this PR but I'd have felt more comfortable with my changes if I could have run this first.
=> JSAPI 3.15

gulpfile.js, site/app/appConfig.js, site/app/examples/vector-tile-basemap.html, site/app/examples/vector-tile-basemap.js, site/index.html, src/core/esriLayerUtils.js, src/layers/EsriLayerControllerBase.js, src/layers/EsriVectorTileLayerController.js, src/layers/esriVectorTileLayer.js, src/map/EsriMapController.js
quick stab at adding a vector tile directive.  Perhaps this is something folk can refine?
I note that the lifecycle doesn't behave quite right - I seem to need to click onto, say, 'Set Basemap' before 'Vector Basemap'.  Perhaps someone can comment.
Happy to rebase as necessary.
=> draft vector tile directive with example

site/app/app.js, site/app/appConfig.js, site/app/examples/feature-layer.html, site/app/examples/home-button.html, site/app/examples/scene-view.html
@tomwayson please review.  This is an attempt at fixing the unneeded presence of `ng-controller` in the example docs pages for v2beta1, while also avoiding any use of `$scope`.  The commit comment should provide a little more info.  This doesn't resolve any open issues; it is just some required maintenance while working on other items.  Thanks.
=> controllers-and-scope

src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, test/feature-layer.html, test/scene-view.html
@tomwayson please review; resolves #203.
I found that it was crucial to keep your original work with getting an immediate reference to a promise for esriLoading a `MapView` or `SceneView` module.  Without this--and instead AMD loading within the `setMap` method--sometimes I'd find myself outside of the Angular digest cycle and nothing would load in a `<esri-*-view>` directive.
Ultimately, this code now _constructs_ a new `MapView` or `SceneView` with all options + a valid map instance inside of the `setMap` method.
Otherwise, just for illustration, I added a button to change the `map` property for the scene-view and feature-layer test pages.  You'll see that the feature-layer test page will not behave :100:% right when attempting to change the map property, and I think this has to do with …
=> View options #203

site/app/examples/chaining-promises.js, site/app/examples/search.js, site/app/examples/webscene-slides.js, src/core/esriLoader.js, test/chaining-promises.html, test/search.html, test/unit/core/esriLoader.spec.js, test/webscene-slides.html
@tomwayson please review.  This resolves #219, using option 2 as we discussed.
The first commit has the standalone changes to `esriLoader.require` and it's unit tests so we can re-use that back to v1.
A couple unit tests have been commented out and I'd appreciate your input on those to help adjust the mocks to get them to work again.
As far as the `esriLoader.require` code changes go, it seems to work well!  It might benefit from cutting out some redundant code, but I couldn't come up with a straightforward way to trim it down.
=> Require callback digest

site/index.html
resolves #226; added autoscroll property to ng-view to scroll to the top on route change
@tomwayson please check it out. No rush. I think it is a decent fix if on a desktop browser, but when it is responsive (e.g. mobile device) the scroll to the top behavior might be jarring.
As an alternative, I played around with the following during the route change listener (see leftNavController.js) to actually scroll to, say an `<h2 id="xyzID">` element in an example page, but I still saw the JSAPI flickering/flashing somtimes.
```javascript
$location.hash('xyzID');
$anchorScroll();
```
=> autoscroll-ngview

site/app/examples/chaining-promises.html, site/app/examples/chaining-promises.js, site/app/examples/extrude-polygon.html, site/app/examples/extrude-polygon.js, site/app/examples/geodesic-buffers.html, site/app/examples/geodesic-buffers.js, site/app/examples/home-button.html, site/app/examples/home-button.js, site/app/examples/scene-toggle-elevation.html, site/app/examples/scene-toggle-elevation.js, site/app/examples/scene-view.html, site/app/examples/scene-view.js, site/app/examples/webscene-slides.html, site/app/examples/webscene-slides.js, site/app/patterns/references-to-views.html, site/styles/main.css, src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, src/map/esriMapView.js, src/map/esriSceneView.js
I actually had to do the following in Chrome (48.0.2564.109):
`chrome://flags/`: Disable 3D software rasterizer (yes, do this)
`chrome://settings/`: Use hardware acceleration when available (you might also have to un-check this)
Resolves #239 
Resolves #240
I tried to split different concerns into different commits:
- I added new info about the `on-error` to the patterns page about the other events, but perhaps that wasn't the perfect place to dump in that new info.
- Also, I don't know of a good way to functionally e2e test the addition of the `on-error` event to the view directives test pages, so only the site examples currently benefit from this.
=> View directives on error

site/index.html, site/styles/main.css
- push left nav below example views on mobile
- snippet tabs show HTML/JS w/ filenames below snippet
- quick fix for top nav sizing on mobile (navbar would have required
ui-bootstrap)
Preview: http://tomwayson.github.io/angular-esri-map/
resolves #241
=> (slightly better) mobile friendly styles/layout

CHANGELOG.md, bower.json, package.json
Proposed changes:
- Should be able to automatically get the Angular dependency when creating a new app with npm or bower.
- test that it works with bower: `bower install angular-esri-map#npm-bower-angular-deps`
- test that it works with npm: `npm install https://github.com/Esri/angular-esri-map.git#npm-bower-angular-deps`
@tomwayson please review
Resolves #275
=> added angular dependency for npm and bower

CHANGELOG.md, site/app/app.js, site/app/appConfig.js, site/app/examples/property-binding.html, site/app/examples/registry-pattern.html, site/app/examples/scene-view.html, site/app/examples/webscene-slides-as-directive.js, site/app/home/home.html, site/app/home/home.js, site/app/patterns/references-to-views.html, site/app/patterns/using-creating-widgets.html, site/docs-resources/esri.core.ngdoc, site/docs-resources/esri.map.ngdoc, site/docs-resources/index.ngdoc, site/index.html, site/styles/main.css, src/core/esriLoader.js, src/core/esriRegistry.js, src/map/EsriHomeButtonController.js, src/map/EsriMapViewController.js, src/map/EsriSceneViewController.js, src/map/EsriWebsceneSlidesController.js, src/map/esriHomeButton.js, src/map/esriMapView.js, src/map/esriSceneView.js, src/map/esriWebsceneSlides.js, test/property-binding.html, test/registry-pattern.html, test/scene-view.html
Proposed changes:
- Standardized references throughout v2 API docs to Esri API by using the full name "Esri ArcGIS API for JavaScript", and to Esri modules by using their proper casing (e.g. "MapView" instead of "map view")
- Tried to add more links back to JSAPI 4 doc pages when referring to Esri modules in the v2 API docs
- Bonus: Added an animated toggle between the two main directives' titles in the home page jumbotron
Resolves #290 
@tomwayson please review, particularly the "Bonus" item.  Is it too much?
=> V2 docs links

CHANGELOG.md, README.md, site/app/examples/vector-tile-layer.html, site/app/examples/vector-tile-layer.js, site/docs-resources/esri.core.ngdoc, site/index.html, src/core/esriLoader.js, src/map/esriMap.js, test/unit/core/esriLoader.spec.js, test/vector-tile-layer.html
- Choose the appropriate base branch that you want to merge into:
- **v1.x** for v1 (Esri JSAPI 3.x)
resolves #304 
Once approved and merged, I can take care of:
=> v1 defaults to JSAPI 3.18

CHANGELOG.md, README.md, site/app/appConfig.js, site/app/examples/extrude-polygon.html, site/app/examples/extrude-polygon.js, site/app/examples/popups.js, site/app/examples/vector-tiles.js, site/app/examples/webscene-slides.html, site/app/examples/webscene-slides.js, site/index.html, src/core/esriLoader.js, test/e2e/specs/popups.js, test/e2e/specs/registry-pattern.js, test/extrude-polygon.html, test/popups.html, test/unit/core/esriLoader.spec.js, test/vector-tiles.html, test/webscene-slides.html
- Choose the appropriate base branch that you want to merge into:
- **master** for v2 (Esri JSAPI 4.x)
resolves #305 
resolves #299 
@tomwayson do you have available bandwidth for a review of this PR?
Once approved and merged, I can take care of:
=> v2 defaults to JSAPI 4.1
